### ISSUE TITLE
Error in data resource adguard_config

### ISSUE THREAD

**Issue by stanislav-bios-baranov** [gmichels/terraform-provider-adguard#95]
Hello. I am using adguard home container `adguard/adguardhome:v0.107.43` (latest) and provider version `1.1.3` (latest)

While trying to have 

```terraform
data "adguard_config" "main" {}
```

I am receiving:

````
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Value Conversion Error
│ 
│   with data.adguard_config.main,
│   on adguard.tf line 1, in data "adguard_config" "main":
│    1: data "adguard_config" "main" {}
│ 
│ An unexpected error was encountered trying to convert from struct value. This is always an error in the provider. Please report the following to the provider developer:
│ 
│ error retrieving field names from struct tags: [0]: need a struct tag for "tfsdk" on Mac
╵
╷
│ Error: Value Conversion Error
│ 
│   with data.adguard_config.main,
│   on adguard.tf line 1, in data "adguard_config" "main":
│    1: data "adguard_config" "main" {}
│ 
│ An unexpected error was encountered while verifying an attribute value matched its expected type to prevent unexpected behavior or panics. This is always an error in the provider. Please report the following to the provider developer:
│ 
│ Expected framework type from provider logic: types.ObjectType["certificate_chain":basetypes.StringType, "dns_names":types.ListType[basetypes.StringType], "enabled":basetypes.BoolType, "force_https":basetypes.BoolType, "issuer":basetypes.StringType, "key_type":basetypes.StringType,
│ "not_after":basetypes.StringType, "not_before":basetypes.StringType, "port_dns_over_quic":basetypes.Int64Type, "port_dns_over_tls":basetypes.Int64Type, "port_https":basetypes.Int64Type, "private_key":basetypes.StringType, "private_key_saved":basetypes.BoolType, "server_name":basetypes.StringType,
│ "subject":basetypes.StringType, "valid_cert":basetypes.BoolType, "valid_chain":basetypes.BoolType, "valid_key":basetypes.BoolType, "valid_pair":basetypes.BoolType, "warning_validation":basetypes.StringType] / underlying type: tftypes.Object["certificate_chain":tftypes.String,
│ "dns_names":tftypes.List[tftypes.String], "enabled":tftypes.Bool, "force_https":tftypes.Bool, "issuer":tftypes.String, "key_type":tftypes.String, "not_after":tftypes.String, "not_before":tftypes.String, "port_dns_over_quic":tftypes.Number, "port_dns_over_tls":tftypes.Number,
│ "port_https":tftypes.Number, "private_key":tftypes.String, "private_key_saved":tftypes.Bool, "server_name":tftypes.String, "subject":tftypes.String, "valid_cert":tftypes.Bool, "valid_chain":tftypes.Bool, "valid_key":tftypes.Bool, "valid_pair":tftypes.Bool, "warning_validation":tftypes.String]
│ Received framework type from provider logic: types.ObjectType[] / underlying type: tftypes.Object[]
│ Path: tls
╵

````

**Comment by gmichels** [comment]
Sorry, I can't reproduce this issue. Just tried on a brand new container and it works just fine.

Maybe you have something special in your config? If you could share the AdGuardHome.yaml file (removing any sensitive info), I could see if I can reproduce.

**Comment by stanislav-bios-baranov** [comment]
Hello @gmichels 

Thanks for fast answer.

I am attaching my stripped config. I have stripped from it my domain name, letsencrypt certificates, names and MACs of devices.


```yaml
http:
  pprof:
    port: 6060
    enabled: false
  address: 192.168.2.12:3000
  session_ttl: 720h
users:
  - name: root
    password: redacted
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: ""
theme: auto
dns:
  bind_hosts:
    - 192.168.2.12
  port: 53
  anonymize_client_ip: false
  ratelimit: 20
  ratelimit_subnet_len_ipv4: 24
  ratelimit_subnet_len_ipv6: 56
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
    - tls://dns.adguard-dns.com
    - https://dns.adguard-dns.com/dns-query
  upstream_dns_file: ""
  bootstrap_dns:
    - 1.1.1.2
    - 1.0.0.2
    - 1.1.1.1
    - 1.0.0.1
  fallback_dns:
    - tls://1dot1dot1dot1.cloudflare-dns.com
    - https://dns.cloudflare.com/dns-query
  all_servers: false
  fastest_addr: false
  fastest_timeout: 1s
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
    - version.bind
    - id.server
    - hostname.bind
  trusted_proxies:
    - 127.0.0.0/8
    - ::1/128
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  cache_optimistic: false
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: false
  edns_client_subnet:
    custom_ip: ""
    enabled: false
    use_custom: false
  max_goroutines: 300
  handle_ddr: true
  ipset: []
  ipset_file: ""
  bootstrap_prefer_ipv6: false
  upstream_timeout: 10s
  private_networks: []
  use_private_ptr_resolvers: false
  local_ptr_upstreams:
    - ""
  use_dns64: false
  dns64_prefixes: []
  serve_http3: false
  use_http3_upstreams: false
tls:
  enabled: true
  server_name: adguard.mydomain
  force_https: false
  port_https: 3001
  port_dns_over_tls: 853
  port_dns_over_quic: 853
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  certificate_chain: |
    -----BEGIN CERTIFICATE-----
    let's encrypt certificate stripped here
    -----END CERTIFICATE-----
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    let's encrypt certificate stripped here
    -----END RSA PRIVATE KEY-----
  certificate_path: ""
  private_key_path: ""
  strict_sni_check: false
querylog:
  ignored: []
  interval: 2160h
  size_memory: 1000
  enabled: true
  file_enabled: true
statistics:
  ignored: []
  interval: 24h
  enabled: true
filters:
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
    name: AdGuard DNS filter
    id: 1
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
    name: AdAway Default Blocklist
    id: 2
whitelist_filters: []
user_rules:
  - '||pikabu.ru^'
  - ""
dhcp:
  enabled: true
  interface_name: eth0
  local_domain_name: lan
  dhcpv4:
    gateway_ip: 192.168.2.1
    subnet_mask: 255.255.255.0
    range_start: 192.168.2.30
    range_end: 192.168.2.250
    lease_duration: 3600
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
filtering:
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_services:
    schedule:
      time_zone: UTC
    ids: []
  protection_disabled_until: null
  safe_search:
    enabled: false
    bing: true
    duckduckgo: true
    google: true
    pixabay: true
    yandex: true
    youtube: true
  blocking_mode: default
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  rewrites: []
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  filters_update_interval: 24
  blocked_response_ttl: 10
  filtering_enabled: true
  parental_enabled: true
  safebrowsing_enabled: true
  protection_enabled: true
clients:
  runtime_sources:
    whois: true
    arp: true
    rdns: true
    dhcp: true
    hosts: true
  persistent:
    - safe_search:
        enabled: true
        bing: true
        duckduckgo: true
        google: true
        pixabay: true
        yandex: true
        youtube: true
      blocked_services:
        schedule:
          time_zone: UTC
        ids: []
      name: Device 1
      ids:
        - 99:99:99:99:99:99
      tags:
        - device_laptop
        - os_other
        - user_child
      upstreams: []
      use_global_settings: false
      filtering_enabled: true
      parental_enabled: true
      safebrowsing_enabled: true
      use_global_blocked_services: true
      ignore_querylog: false
      ignore_statistics: false
    - safe_search:
        enabled: true
        bing: true
        duckduckgo: true
        google: true
        pixabay: true
        yandex: true
        youtube: true
      blocked_services:
        schedule:
          time_zone: UTC
        ids: []
      name: Device 2
      ids:
        - 99:99:99:99:99:98
      tags:
        - device_phone
        - os_android
        - user_child
      upstreams: []
      use_global_settings: false
      filtering_enabled: true
      parental_enabled: true
      safebrowsing_enabled: true
      use_global_blocked_services: true
      ignore_querylog: false
      ignore_statistics: false
    - safe_search:
        enabled: false
        bing: false
        duckduckgo: false
        google: false
        pixabay: false
        yandex: false
        youtube: false
      blocked_services:
        schedule:
          time_zone: UTC
        ids: []
      name: Device 3
      ids:
        - 99:99:99:99:99:97
        - 192.168.2.36
      tags:
        - device_phone
        - os_ios
        - user_regular
      upstreams: []
      use_global_settings: false
      filtering_enabled: true
      parental_enabled: false
      safebrowsing_enabled: true
      use_global_blocked_services: true
      ignore_querylog: false
      ignore_statistics: false
    - safe_search:
        enabled: true
        bing: true
        duckduckgo: true
        google: true
        pixabay: true
        yandex: true
        youtube: true
      blocked_services:
        schedule:
          time_zone: UTC
        ids: []
      name: Device 4
      ids:
        - 99:99:99:99:99:96
      tags:
        - device_phone
        - os_android
        - user_child
      upstreams: []
      use_global_settings: false
      filtering_enabled: true
      parental_enabled: true
      safebrowsing_enabled: true
      use_global_blocked_services: true
      ignore_querylog: false
      ignore_statistics: false
    - safe_search:
        enabled: false
        bing: false
        duckduckgo: false
        google: false
        pixabay: false
        yandex: false
        youtube: false
      blocked_services:
        schedule:
          time_zone: UTC
        ids: []
      name: Device 5
      ids:
        - 99:99:99:99:99:95
        - 192.168.2.38
      tags:
        - device_phone
        - os_ios
        - user_admin
      upstreams: []
      use_global_settings: true
      filtering_enabled: true
      parental_enabled: false
      safebrowsing_enabled: true
      use_global_blocked_services: true
      ignore_querylog: false
      ignore_statistics: false
    - safe_search:
        enabled: false
        bing: true
        duckduckgo: true
        google: true
        pixabay: true
        yandex: true
        youtube: true
      blocked_services:
        schedule:
          time_zone: UTC
        ids: []
      name: Device 6
      ids:
        - 99:99:99:99:99:94
        - 192.168.2.17
      tags:
        - device_laptop
        - os_linux
        - user_admin
      upstreams: []
      use_global_settings: true
      filtering_enabled: false
      parental_enabled: false
      safebrowsing_enabled: false
      use_global_blocked_services: true
      ignore_querylog: false
      ignore_statistics: false
    - safe_search:
        enabled: false
        bing: true
        duckduckgo: true
        google: true
        pixabay: true
        yandex: true
        youtube: true
      blocked_services:
        schedule:
          time_zone: UTC
        ids: []
      name: Device 7
      ids:
        - 99:99:99:99:99:93
      tags:
        - device_laptop
        - os_linux
        - user_admin
      upstreams: []
      use_global_settings: true
      filtering_enabled: false
      parental_enabled: false
      safebrowsing_enabled: false
      use_global_blocked_services: true
      ignore_querylog: false
      ignore_statistics: false
    - safe_search:
        enabled: false
        bing: true
        duckduckgo: true
        google: true
        pixabay: true
        yandex: true
        youtube: true
      blocked_services:
        schedule:
          time_zone: UTC
        ids: []
      name: Device 8
      ids:
        - 99:99:99:99:99:92
        - 192.168.2.11
      tags:
        - os_macos
        - user_admin
      upstreams: []
      use_global_settings: false
      filtering_enabled: true
      parental_enabled: false
      safebrowsing_enabled: true
      use_global_blocked_services: true
      ignore_querylog: false
      ignore_statistics: false
    - safe_search:
        enabled: false
        bing: false
        duckduckgo: false
        google: false
        pixabay: false
        yandex: false
        youtube: false
      blocked_services:
        schedule:
          time_zone: UTC
        ids: []
      name: Device 9
      ids:
        - 99:99:99:99:99:91
        - 192.168.2.16
      tags:
        - device_printer
      upstreams: []
      use_global_settings: true
      filtering_enabled: false
      parental_enabled: false
      safebrowsing_enabled: false
      use_global_blocked_services: true
      ignore_querylog: false
      ignore_statistics: false
log:
  file: ""
  max_backups: 0
  max_size: 100
  max_age: 3
  compress: false
  local_time: false
  verbose: false
os:
  group: ""
  user: ""
  rlimit_nofile: 0
schema_version: 27
```
